name: Test GL SDK

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Clone GL SDK
        run: |
          git clone https://github.com/gl-inet/sdk.git

      - name: Download MT1300 SDK
        run: |
          cd sdk
          chmod +x download.sh
          ./download.sh ramips-1907

      - name: Show SDK structure
        run: |
          find sdk -maxdepth 4

      - name: Show SDK info
        run: |
          echo "===== SDK Directory ====="
          find sdk -maxdepth 3 -type d

          echo
          echo "===== feeds.conf.default ====="
          find sdk -name feeds.conf.default -exec cat {} \;

          echo
          echo "===== OpenWrt Version ====="
          find sdk -name version.mk -exec cat {} \;
